server:
  port: 8080

spring:
  application:
    name: todo-list-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mail:
    host: smtp.qq.com # 或者 smtp.163.com / smtp.gmail.com
    username: 1489027718@qq.com  # 替换为你的邮箱
    password: yudyekdhtokubabh  # 替换为你的 SMTP 授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
